# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely need to edit after that.
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'jekyll serve'. If you change this file, please restart the server process.

# Site settings
title: Cristian Gutiérrez
email: neo.madara@gmail.com
description: > # this means to ignore newlines until "baseurl:"
  Soy un Dev con mucha pasión por el código y las nuevas tecnologías, en mi tiempo libre
  me dedico a expandar mis conocimientos y divertirme dejando salir mi lado Gamer ;)
baseurl: "" # the subpath of your site, e.g. /blog
url: "https://neomadara.github.io/" # the base hostname & protocol for your site
twitter_username: CristGutierrez
github_username:  neomadara

# Build settings
markdown: kramdown
